---
title: "Reproducible Research: Peer Assessment 1"
output: html_document: keep_md: true
---
setwd("C:/dev/R/reproducible-research/RepData_PeerAssessment1")
library(knitr)
opts_chunk$set(fig.path='fig/')


#Introduction

It is now possible to collect a large amount of data about personal movement using activity monitoring devices such as a Fitbit, Nike Fuelband, or Jawbone Up. These type of devices are part of the "quantified self" movement - a group of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their behavior, or because they are tech geeks. But these data remain under-utilized both because the raw data are hard to obtain and there is a lack of statistical methods and software for processing and interpreting the data.

This assignment makes use of data from a personal activity monitoring device. This device collects data at 5 minute intervals through out the day. The data consists of two months of data from an anonymous individual collected during the months of October and November, 2012 and include the number of steps taken in 5 minute intervals each day.

The variables included in this dataset are:
    steps: Number of steps taking in a 5-minute interval (missing values are coded as NA)
    date: The date on which the measurement was taken in YYYY-MM-DD format
    interval: Identifier for the 5-minute interval in which measurement was taken

The dataset is stored in a comma-separated-value (CSV) file and there are a total of 17,568 observations in this dataset.

#Data
The data for this assignment can be downloaded from the course web site:  
- Dataset: [Activity monitoring data](https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip)

#For a complete processing, please execute project.R

## Loading and preprocessing the data
library(lattice)                        
rm(list = ls())                         
setwd("C:/dev/R/reproducible-research/RepData_PeerAssessment1") 
if ( !file.exists("activity.csv") )
{
    localFile <- paste(getwd(),"/activity.zip",sep = "")
    
    if ( !file.exists("activity.zip") )
    {
        
        download.file("https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip",
                      destfile = localFile)
    }
        
    # and unzip it to our local folder as well.
    unzip(localFile)
}
inputData <- read.csv('activity.csv')
aggrStepsByDay <- with( inputData,
                        aggregate(steps ~ date, 
                                  data = inputData, 
                                  FUN = "sum", 
                                  na.rm = TRUE ))

## What is mean total number of steps taken per day?
meanSteps <- mean(aggrStepsByDay$steps)

## What is the average daily activity pattern?
hist(aggrStepsByDay$steps,
     main = "2. Total Number of Steps by day",
     xlab = "Steps" )

## Inputing missing values
filledData <- inputData
fiveMinIntervalStepsAverage <- with( inputData, 
                                     aggregate(steps ~ interval, 
                                               data = inputData, 
                                               FUN = "mean", 
                                               na.rm = TRUE) )
filledData$steps[is.na(filledData$steps)] <- fiveMinIntervalStepsAverage$steps
complStepsByDay <- with( filledData, 
                         aggregate(steps ~ date, 
                                   data = filledData, 
                                   FUN = "sum", 
                                   na.rm = TRUE) )  


## Are there differences in activity patterns between weekdays and weekends?
filledDataLen <- length(filledData$date)
filledData$DayType <- 0 
for ( pos in 1:filledDataLen )
{
    filledData$DayType[pos] <- ifelse( with(filledData, weekdays( as.Date( date[pos] ) ) ) < "Saturday", "Weekday", "Weekend") 
}
dayTypeNewAvg <- aggregate(steps ~ interval + DayType,
                           data = filledData, 
                           FUN = "mean", 
                           na.rm = TRUE)
with( dayTypeNewAvg, 
      xyplot(steps ~ interval | DayType, 
             data = dayTypeNewAvg, 
             type = "l", 
             layout = c(1, 2), 
             xlab = "Interval", 
             ylab = "Steps" ) )
